spring.main.web-application-type=none
candidate.name=John Doe
candidate.regNo=REG12347
candidate.email=john@example.com
candidate.sqlPath=sql/final-query.sql
api.generateWebhookUrl=https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA
api.testWebhookUrl=https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA
logging.level.root=INFO

